# Generated by Django 4.0.3 on 2022-04-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
