# Generated by Django 4.0.3 on 2022-04-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='date_of_reminder',
            new_name='start_of_reminder',
        ),
        migrations.AddField(
            model_name='reminder',
            name='end_of_reminder',
            field=models.DateField(null=True),
        ),
    ]
